version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    networks:
      - bookstore-net

  book-service:
    build: ./book-service
    ports:
      - "3002:3002"
    networks:
      - bookstore-net

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    networks:
      - bookstore-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - bookstore-net
    depends_on:
      - auth-service
      - book-service
      - order-service

networks:
  bookstore-net:
    driver: bridge
